### PR TITLE
Add between method to expression builder

### PR DESCRIPTION
**Pull request by koskimas**
Don't know if this is a good DX. Feel free to shoot this down.

### CODE REVIEW

**Review by igalklebanov — APPROVED** [review]
I was praying and hoping for this day to come. 😄 

My beloved `between`!!!! ✨ 

Looks good to me! 🚀 

One thing to consider, PostgreSQL supports a [`between symmetric`](https://andreigridnev.com/blog/2016-03-20-between-symmetric-operator-in-postgresql/) that should be a great QoL solution (no need to compare inputs before querying).

How would we tackle this? maybe..

```ts
eb.betweenSymmetric(expr, start, end)
// or
eb.between(expr, start, end).symmetric()
```

**Comment by koskimas** [comment]
Maybe `eb.betweenSymmetric(expr, start, end)` would be the lesser evil? Should I add it?

**Comment by igalklebanov** [comment]
> Maybe `eb.betweenSymmetric(expr, start, end)` would be the lesser evil? Should I add it?

Yeah, seems like an easy win.

**Comment by koskimas** [comment]
> I was praying and hoping for this day to come.

The only reason I was agains `between` was that I didn't want to add `whereBetween`, `orWhereBetween`, `onBetween` etc. everywhere. In the expression builder, it's an easy and natural addition.

**Comment by igalklebanov** [comment]
@frencojobs release pending.

**Comment by csulit** [comment]
I hope we get this. 😁

**Pull request merged**
