### PR TITLE
Migrate to new playground

### PR DESCRIPTION
**Pull request by wirekang**

### CODE REVIEW

**Comment by koskimas** [comment]
Is this actually still a draft or could this be merged?

**Comment by wirekang** [comment]
I'm cautious about ruining website by new playground. Waiting critical issues to be found.

**Comment by igalklebanov** [comment]
Resolved conflicts after bumping docusaurus to v3.

**Comment by koskimas** [comment]
@igalklebanov Could we merge this? kysely.dev is stuck in 0.27.2 with the old version.

**Comment by wirekang** [comment]
No problem.

**Pull request merged**
