### PR TITLE
add node20 to workflows, drop node14, bump better-sqlite3 to v8.

### PR DESCRIPTION
**Pull request by igalklebanov**
Node.js LTS is v18, current is v20. v14 was April 30, 2023.

Let's ditch node 14 from our required tests in CI. Replace it with node 20.

This PR also bumps `better-sqlite3` to latest v8 to get node20 compatible binaries.

postrequisites:

- add `run-tests (20.x, 1.19.x)` to required PR checks.
- remove `run-tests (14.x, 1.19.x)` from required PR checks.

### CODE REVIEW

**Comment by koskimas** [comment]
Seems like there's no prebuilt package for for better-sqlite yet?

**Comment by igalklebanov** [comment]
> Seems like there's no prebuilt package for for better-sqlite yet?

On the way https://github.com/WiseLibs/better-sqlite3/pull/1000 ✈️

**Comment by nikeee** [comment]
Pre-Built binaries should be available now. Can we re-trigger CI?

**Comment by igalklebanov** [comment]
> Pre-Built binaries should be available now. Can we re-trigger CI?

Done, thank you!

**Pull request merged**
