### PR TITLE
Updated TraversedJSONPathBuilder.$castTo and .$notNull to support chaining with .as()

### LINKED ISSUE #1138: TraversedJSONPathBuilder.$castTo and .$notNull should return TraversedJSONPathBuilder instead of JSONPathBuilder?
Hi,

#### `TraversedJSONPathBuilder.as` typechecks correctly:

```ts
eb
  .ref("healthScaleStepJson.healthScaleStepJson", "->>")
  .key("id")
  .as("formComponentId"),
```

#### `TraversedJSONPathBuilder.$castTo` typechecks correctly:

```ts
eb
  .ref("healthScaleStepJson.healthScaleStepJson", "->>")
  .key("id")
  .$castTo<FormComponentId>()
```

#### But when `.$castTo` and `.as` is combined it's a type error
```ts
eb
  .ref("healthScaleStepJson.healthScaleStepJson", "->>")
  .key("id")
  .$castTo<FormComponentId>()
  .as("formComponentId"), // <--- Property 'as' does not exist on type 'JSONPathBuilder
```

My guess is that this could be fixed if `TraversedJSONPathBuilder`.`$castTo` (and .`$notNull` which is very similar) returned `TraversedJSONPathBuilder` instead of `JSONPathBuilder`.

### PR DESCRIPTION
**Pull request by cassus**
closes #1138

i hope :)

## TODO

- [x] add test

### CODE REVIEW

**Comment by aphex** [comment]
👀

**Comment by cassus** [comment]
I'm ready for you review @aphex

**Comment by aphex** [comment]
@cassus likely not me you're looking for, I am just a lowly interested party on this one haha. Ran into the same issue and wanted to see it cleared up. Your tests seem to cover the situation I am struggling with, so 👍 from me, but sadly I have no power here :)

**Review by igalklebanov — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
