### PR TITLE
fix: fixed ES Module loading with abolute path fails on windows

### PR DESCRIPTION
**Pull request by MrMenezesDev**
Fixed error on windows

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
    at defaultResolve (node:internal/modules/esm/resolve:1135:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at defer (C:\Projetos\cubos\api-typescript-sdkgen-kysely\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.49_@types+node@18.15.11_typescript@4.9.5\node_modules\ts-node\src\esm.ts:159:23)
    at entrypointFallback (C:\Projetos\cubos\api-typescript-sdkgen-kysely\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.49_@types+node@18.15.11_typescript@4.9.5\node_modules\ts-node\src\esm.ts:168:34)
    at C:\Projetos\cubos\api-typescript-sdkgen-kysely\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.49_@types+node@18.15.11_typescript@4.9.5\node_modules\ts-node\src\esm.ts:202:16
    at addShortCircuitFlag (C:\Projetos\cubos\api-typescript-sdkgen-kysely\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.49_@types+node@18.15.11_typescript@4.9.5\node_modules\ts-node\src\esm.ts:409:21)
    at resolve (C:\Projetos\cubos\api-typescript-sdkgen-kysely\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.49_@types+node@18.15.11_typescript@4.9.5\node_modules\ts-node\src\esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/loader:163:28)

### CODE REVIEW

**Comment by koskimas** [comment]
And breaks migration on all other platforms...

**Comment by MrMenezesDev** [comment]
Is there any platform identifier in any utils module that you can use?

**Comment by koskimas** [comment]
Unfortunately no since Kysely is platform independent. There's no API (that I know of) that works on node, deno, bun, the browsers and all other javascript environments that can be used to check the platform.

**Comment by mtt-artis** [comment]
i link this for info https://github.com/nodejs/node/issues/31710

**Comment by mtt-artis** [comment]
@koskimas 
actually "file://" works on windows and linux in esm
this would work fine
```ts
const isEsm = Boolean(typeof module !== 'undefined' && typeof module.imports !== 'undefined') 
this.#props.path.join(
  isEsm ? "file://" : "",
  this.#props.migrationFolder,
  fileName
)
```

**Pull request closed without merging**
